//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cuahangtaphoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string MaVach { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public Nullable<int> MaNhaCungCap { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public decimal GiaBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> SoLuongToiThieu { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
